#import "../connection.gql"
#import "../article/digest.gql"
#import "./digest.gql"
#import "../comment/digest.gql"

fragment UserDetail on User {
  id
  uuid
  userName
  remark
  info {
    createdAt
    userName
    userNameEditable
    displayName
    description
    avatar
    email
    emailVerified
    mobile
  }
  settings {
    language
  }
  status {
    state
    MAT {
      total
    }
    articleCount
    # viewCount
    # draftCount
    commentCount
    # quotationCount
    subscriptionCount
    followeeCount
    followerCount
    invitation {
      left
      sent(input: { first: null }) {
        edges {
          node {
            id
            user {
              ...UserDigest
            }
            email
            accepted
            createdAt
          }
        }
      }
    }
  }
  articles(input: { first: 20 }) {
    ...ConnectionInfo
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
  commentedArticles(input: { first: null }) {
    ...ConnectionInfo
    edges {
      cursor
      node {
        ...ArticleDigest
        comments(input: { filter: { author: $author }, first: null }) {
          edges {
            cursor
            node {
              ...CommentDigest
            }
          }
        }
      }
    }
  }
  # subscriptions(input: { first: 20 }) {
  #   ...ConnectionInfo
  #   edges {
  #     node {
  #       ...ArticleDigest
  #     }
  #   }
  # }
}
