#import "../connection.gql"
#import "../article/digest.gql"

fragment UserDetail on User {
  id
  uuid
  userName
  displayName
  avatar
  remark
  liker {
    likerId
  }
  info {
    createdAt
    userNameEditable
    description
    badges {
      type
    }
  }
  settings {
    language
  }
  status {
    role
    state
    articleCount
    commentCount
  }
  oss {
    boost
  }
  followees(input: { first: 0 }) {
    ...ConnectionInfo
  }
  followers(input: { first: 0 }) {
    ...ConnectionInfo
  }
  articles(input: { first: 20 }) {
    ...ConnectionInfo
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
}
