#import "../connection.gql"
#import "../article/digest.gql"

fragment UserDetail on User {
  id
  userName
  displayName
  avatar
  remark
  liker {
    likerId
  }
  info {
    createdAt
    userNameEditable
    description
    badges {
      type
    }
    ethAddress
    cryptoWallet {
      address
    }
  }
  settings {
    language
  }
  status {
    role
    state
    articleCount
    commentCount
  }
  oss {
    boost
  }
  followers(input: { first: 0 }) {
    ...ConnectionInfo
  }
  following {
    users(input: { first: 0 }) {
      ...ConnectionInfo
    }
  }
  articles(input: { first: 20 }) {
    ...ConnectionInfo
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
}
