fragment UserDigest on User {
  id
  uuid
  userName
  displayName
  info {
    createdAt
    description
    badges {
      type
    }
  }
  status {
    state
    articleCount
    commentCount
  }
}
