fragment UserDigest on User {
  id
  uuid
  userName
  info {
    userName
    displayName
    description
    email
  }
  status {
    state
    articleCount
    commentCount
    MAT {
      total
    }
  }
}
