#import "../connection.gql"
#import "../user/digest.gql"
#import "./digest.gql"

fragment ArticleDetail on Article {
  ...ArticleDigest
  cover
  summary
  wordCount
  dataHash
  mediaHash
  content
  MAT
  participantCount
  appreciatorCount
  subscribed
  hasAppreciate
  remark
  # relatedArticles(input: { first: 20 }) {
  #   ...ConnectionInfo
  #   edges {
  #     node {
  #       ...ArticleDigest
  #     }
  #   }
  # }
  subscribers(input: { first: 20 }) {
    ...ConnectionInfo
    edges {
      node {
        ...UserDigest
      }
    }
  }
  appreciators(input: { first: 20 }) {
    edges {
      node {
        ...UserDigest
      }
    }
  }
  oss {
    inRecommendToday
    todayCover
  }
}
