#import "../connection.gql"
#import "../user/digest.gql"
#import "./digest.gql"
#import "../comment/digest.gql"

fragment ArticleDetail on Article {
  ...ArticleDigest
  cover
  summary
  wordCount
  dataHash
  mediaHash
  content
  MAT
  collection(input: { first: null }) {
    ...ConnectionInfo
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
  collectedBy(input: { first: null }) {
    ...ConnectionInfo
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
  participantCount
  appreciatorCount
  subscribed
  hasAppreciate
  remark
  subscribers(input: { first: null }) {
    ...ConnectionInfo
    edges {
      node {
        ...UserDigest
      }
    }
  }
  appreciators(input: { first: null }) {
    edges {
      node {
        ...UserDigest
      }
    }
  }
  comments(input: { first: null }) {
    edges {
      node {
        ...CommentDigest
      }
    }
  }
  oss {
    inRecommendToday
    todayCover
  }
}
