#import "../user/id.gql"
#import "../tag/id.gql"

fragment ArticleDigest on Article {
  id
  slug
  mediaHash
  title
  createdAt
  state
  commentCount
  author {
    ...UserId
  }
  tags {
    ...TagId
  }
  oss {
    boost
    score
    inRecommendIcymi
    inRecommendHottest
    inRecommendNewest
    inSearch
    spamStatus {
      score
      isSpam
    }
  }
}
