kind: pipeline
name: default

steps:
  - name: node_modules
    image: node:12.16
    commands:
      - npm install --no-progress --quiet --unsafe-perm >  npm-install.log

  # === CI tasks for `develop` branch ===
  - name: develop:build
    image: node:12.16
    commands:
      - npm run build:develop
    when:
      branch:
        - develop

  - name: develop:deploy
    image: plugins/s3
    settings:
      bucket: oss-develop.matters.news
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: ap-southeast-1
      source: build/**/*
      target: /
      strip_prefix: build/
    when:
      branch:
        - develop
      event:
        - push

  # === CI tasks for `master` branch
  - name: prod:build
    image: node:12.16
    commands:
      - npm run build:production
    when:
      branch:
        - master

  - name: prod:deploy
    image: plugins/s3
    settings:
      bucket: oss.matters.news
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: ap-southeast-1
      source: build/**/*
      target: /
      strip_prefix: build/
    when:
      branch:
        - master
      event:
        - push

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: log_github
    username: Drone CI
    when:
      status: [success, failure]
