fragment IcymiTopicDetail on IcymiTopic {
       id
       title
       articles {
          id
          title
       }
       pinAmount
       note
       state
       publishedAt
       archivedAt
}
