query AnnouncementDetail($input: AnnouncementsInput!) {
  official {
    announcements(input: $input) {
      id
      cover
      link
      type
      visible
      order
      createdAt
      updatedAt
    }
  }
}
