query AnnouncementDetail($input: AnnouncementsInput!) {
  official {
    announcements(input: $input) {
      id
      title
      cover
      content
      link
      type
      visible
      order
      translations {
        title
        cover
        content
        link
        language
      }
      createdAt
      updatedAt
    }
  }
}
