query Announcements {
  official {
    announcements(input: {}) {
      id
      title
      cover
      content
      link
      type
      visible
      order
      translations {
        title
        content
        link
        language
      }
      createdAt
      updatedAt
    }
  }
}
