#import "../fragments/connection.gql"
#import "../fragments/article/digest.gql"

query OSSArticleList($input: ConnectionArgs!) {
  oss {
    articles(input: $input) {
      ...ConnectionInfo
      edges {
        node {
          ...ArticleDigest
        }
      }
    }
  }
}
