query OSSIcymiTopicDetail($input: NodeInput!) {
  node(input: $input) {
    ... on IcymiTopic {
       id
       title
       articles {
          id
          title
       }
       pinAmount
       note
       state
       publishedAt
       archivedAt
    }
  }
}
