#import "../fragments/connection.gql"

query OSSIcymiTopicList($input: ConnectionArgs!) {
  oss {
    icymiTopics(input: $input) {
      ...ConnectionInfo
      edges {
        node {
          id
          title
          state
          publishedAt
          archivedAt
        }
      }
    }
  }
}

