#import "../fragments/connection.gql"
#import "../fragments/article/digest.gql"

query OSSRecommendToday($input: ConnectionArgs!) {
  oss {
    today(input: $input) {
      ...ConnectionInfo
      edges {
        node {
          ...ArticleDigest
          oss {
            inRecommendToday
          }
        }
      }
    }
  }
}
