#import "../fragments/connection.gql"
#import "../fragments/user/digest.gql"

query OSSRecommendAuthors($input: AuthorsInput!) {
  viewer {
    id
    recommendation {
      authors(input: $input) {
        ...ConnectionInfo
        edges {
          node {
            ...UserDigest
            oss {
              boost
              score
            }
          }
        }
      }
    }
  }
}
