#import "../fragments/connection.gql"
#import "../fragments/article/digest.gql"

query OSSRecommendTopics($input: ConnectionArgs!) {
  viewer {
    id
    recommendation {
      topics(input: $input) {
        ...ConnectionInfo
        edges {
          node {
            ...ArticleDigest
            oss {
              boost
              score
            }
          }
        }
      }
    }
  }
}
