#import "../fragments/connection.gql"
#import "../fragments/tag/digest.gql"

query OSSRecommendTags($input: RecommendationTagsInput!) {
  viewer {
    id
    recommendation {
      tags(input: $input) {
        ...ConnectionInfo
        edges {
          node {
            ...TagDigest
            oss {
              boost
              score
            }
          }
        }
      }
    }
  }
}
