#import "../fragments/connection.gql"
#import "../fragments/user/digest.gql"

query OSSSearchUsers($input1: SearchInput!, $input2: UserInput!) {
  search(input: $input1) {
    ...ConnectionInfo
    edges {
      node {
        ... on User {
          ...UserDigest
          oss {
            boost
          }
        }
      }
    }
  }
  user(input: $input2) {
    ...UserDigest
    oss {
      boost
    }
  }
}
