#import "../article/digest.gql"
#import "../user/digest.gql"
#import "../user/digest.gql"
#import "./digest.gql"

fragment CampaignDetail on WritingChallenge {
  id
  ...CampaignDigest
  description(input: { language: zh_hant })
  descriptionEn: description(input: { language: en })
  descriptionZhHans: description(input: { language: zh_hans })
  cover
  link
  stages {
    id
    name(input: { language: zh_hant })
    nameEn: name(input: { language: en })
    nameZhHans: name(input: { language: zh_hans })
    period {
      start
      end
    }
  }
  participants(input: { first: null, oss: true }) {
    edges {
      application {
        state
        createdAt
      }
      node {
        ...UserDigest
      }
    }
  }
  articles(input: { first: null }) {
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
}


