#import "../article/digest.gql"
#import "../user/digest.gql"
#import "./digest.gql"

fragment CampaignDetail on WritingChallenge {
  id
  ...CampaignDigest
  description
  cover
  link
  stages {
    id
    name
    period {
      start
      end
    }
  }
  participants(input: { first: null }) {
    edges {
      node {
        ...UserDigest
      }
    }
  }
  articles(input: { first: null }) {
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
}


