#import "../connection.gql"
#import "../article/digest.gql"

fragment TagDetail on Tag {
  id
  content
  createdAt
  description
  articles(input: { first: 20 }) {
    ...ConnectionInfo
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
  oss {
    boost
    score
  }
  remark
  deleted
  creator {
    id
    userName
    displayName
  }
  editors {
    id
    userName
    displayName
  }
}
