#import "../connection.gql"
#import "../article/digest.gql"

fragment TagDetail on Tag {
  id
  content
  createdAt
  articles(input: { first: 20 }) {
    ...ConnectionInfo
    edges {
      node {
        ...ArticleDigest
      }
    }
  }
  remark
}
