#import "../article/digest.gql"
#import "../user/id.gql"

fragment CommentDetail on Comment {
  id
  commentState: state
  createdAt
  node {
    id
    ... on Article {
      ...ArticleDigest
    }
  }
  content
  author {
    ...UserId
  }
  pinned
  upvotes
  downvotes
}
