#import "../article/digest.gql"
#import "../user/id.gql"

fragment CommentDigest on Comment {
  id
  content
  commentState: state
  createdAt
  node {
    id
    ... on Article {
      ...ArticleDigest
    }
  }
  author {
    ...UserId
  }
  pinned
  upvotes
  downvotes
  __typename
}
