#import "../article/digest.gql"
#import "../user/id.gql"

fragment CommentDigest on Comment {
  id
  content
  state
  createdAt
  article {
    ...ArticleDigest
  }
  author {
    ...UserId
  }
  pinned
  upvotes
  downvotes
}
